Story1_app/urls.py
from django.urls import path
from . import views

app_name = 'Story1_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    # dilanjutkan ...
]

Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/',include('Story1_app.urls')),
    path('jadwal/',include('jadwal.urls'))
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('favorit/', views.favorit, name='favorit'),
    # dilanjutkan ...
]

jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'

urlpatterns = [
    path('', views.jadwal_view,name='jadwal_url'),
    path('jadwal/', views.jadwal_view),
    path('detail/<int:pk>',views.detail, name="detail"),
    path('<int:pk>', views.delete, name="hapus"),

  
]

Story1_app/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class jadwal_kuliah(models.Model):
    mata_kuliah = models.CharField(blank=False, max_length= 100)
    dosen_pengajar = models.CharField(blank=False, max_length= 100)
    jumlah_sks = models.CharField(blank=False, max_length= 100)
    jam_kelas = models.CharField(blank=False, max_length= 100)
    semester_tahun = models.CharField(blank=False, max_length= 100)
    deskripsi = models.CharField(blank=False, max_length= 100, default='0000000')

jadwal/forms.py
from django import forms

class formulirku(forms.Form):
    mata_kuliah = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Mata Kuliah',
        'type' : 'text',
        'required' : True
    }))
    dosen_pengajar = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Dosen Pengajar',
        'type' : 'text',
        'required' : True
    }))
    jumlah_sks = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True
    }))
    jam_kelas = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jam Kelas',
        'type' : 'text',
        'required' : True
    }))
    semester_tahun = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Semester Tahun',
        'type' : 'text',
        'required' : True
    }))
    deskripsi = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Deskripsi',
        'type' : 'text',
        'required' : True
    }))

Story1_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'Story1.html')

def about(request):
    return render(request, 'Story1_About.html')

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'Story3.html')

def favorit(request):
    return render(request,'Story3_Fav.html')

jadwal/views.py
from django.shortcuts import render, redirect
from . import forms, models


# Create your views here.
def jadwal_view(request):
    if(request.method == "POST"):
        tmp = forms.formulirku(request.POST)
        if(tmp.is_valid()):
            model_jadwal = models.jadwal_kuliah()
            model_jadwal.mata_kuliah = tmp.cleaned_data["mata_kuliah"]
            model_jadwal.dosen_pengajar= tmp.cleaned_data["dosen_pengajar"]
            model_jadwal.jumlah_sks = tmp.cleaned_data["jumlah_sks"]
            model_jadwal.jam_kelas = tmp.cleaned_data["jam_kelas"]
            model_jadwal.semester_tahun = tmp.cleaned_data["semester_tahun"]
            model_jadwal.deskripsi = tmp.cleaned_data["deskripsi"]
            model_jadwal.save()
        return redirect("/jadwal")
    else:
        form = forms.formulirku()
        data_matkul = models.jadwal_kuliah.objects.all()
        context = {
            'formulir' : form,
            'jadwal' : data_matkul
        }
        return render(request, 'jadwalku.html', context)

#untuk delete 
def delete(request, pk):
    if (request.method == "POST"):
        form = forms.formulirku(request.POST)
        if(form.is_valid()):
            model_jadwal = models.jadwal_kuliah()
            model_jadwal.mata_kuliah = form.cleaned_data["mata_kuliah"]
            model_jadwal.dosen_pengajar = form.cleaned_data["dosen_pengajar"]
            model_jadwal.jumlah_sks = form.cleaned_data["jumlah_sks"]
            model_jadwal.jam_kelas = form.cleaned_data["jam_kelas"]
            model_jadwal.semester_tahun= form.cleaned_data["semester_tahun"]
            model_jadwal.deskripsi= form.cleaned_data["deskripsi"]
            model_jadwal.save()
        return redirect ("/jadwal")
    else:
        models.jadwal_kuliah.objects.filter(pk = pk).delete()
        form = forms.formulirku()
        data_matkul = models.jadwal_kuliah.objects.all()
        context_delete ={
            "jadwal" : data_matkul,
            "formulir": form
        }
        return render(request, 'jadwalku.html', context_delete)


#detail
def detail(request, pk):
    matkul = models.jadwal_kuliah.objects.get(pk=pk)
    context_detail= {
        "matkul" : matkul,

    }
    return render(request, 'detail.html', context_detail)

Story1_app/templates/Story1.html
<!DOCTYPE html>
<html>
	{% load static %}
	<title>Website ku </title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
			<style>
				/* Style the top navigation bar */
				
				body,html{
					height: 100%;
					margin: 0;
					font-family: Arial, Helvetica, sans-serif;
				}
					

					.bg-image {
					  /* Full height */
						height: 100%;
						background-position: center;
						background-repeat: no-repeat;
						background-size: cover;
					}

					/* Images used */
					.img1 { background-image: url("/static/Galaxy_Green.jpg"); }
				
					

					/* Position text in the middle of the page/image */
					.bg-text {
					  color: white;
					  font-weight: bold;
					  font-size: 80px;
					  position: absolute; /* Stay fixed */
					  top: 30%;
					  left: 50%;
					  transform: translate(-50%, -50%);
					  z-index: 2;
					  width: 300px;
					  padding: 20px;
					  text-align: center;
					}

					.bg-text2 {
					  color: white;
					  font-weight: bold;
					  font-size: 80px;
					  position: absolute; /* Stay fixed */
					  top: 50%;
					  left: 50%;
					  transform: translate(-50%, -50%);
					  z-index: 2;
					  width: 300px;
					  padding: 20px;
					  text-align: center;
					}

					.bg-text3 {
					  color: white;
					  font-weight: bold;
					  font-size: 80px;
					  position: absolute; /* Stay fixed */
					  top: 70%;
					  left: 50%;
					  transform: translate(-50%, -50%);
					  z-index: 2;
					  width: 300px;
					  padding: 20px;
					  text-align: center;
					}			
					.fotobulat {
  					vertical-align: left;
  					width: 100px;
 					height: 100px;
  					border-radius: 50%;	
					position : relative;
					left : 1100px;
					top : 30px;
					}	
			</style>
			
	<head>
		{% include 'base.html' %}
	</head>
	<body>
		<div class="bg-image img1">
			<img src = "{% static 'fotoku.jpg' %}" class = "fotobulat" >
			<div class="bg-text">Hi.</div> 
			<div class="bg-text2">Ola.</div> 
			<div class="bg-text3">Bonjour.</div>
		</div>
	</body>
	</html> 

Story1_app/templates/Story1_About.html
<html>
  {% load static %}
	<head>
    <script src="https://kit.fontawesome.com/a48052e337.js" crossorigin="anonymous"></script>
		<style> 
		  body, html {
			  height: 100%;
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
			}
			.bg-image {
			  height: 100%;
			  background-position: center;
			  background-repeat: no-repeat;
			  background-size: cover;
			}

      .img1 { background-image: url("/static/Galaxy_Green.jpg"); }
		  
      .bg-text {
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0, 0.4);
        color: white;
        font-weight: bold;
        border: 3px solid #f1f1f1;
        position: absolute;
        top: 60%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 2;
        width: 80%;
        padding: 20px;
        text-align: center;
      }

    .container{

        width: 50%;
        height: 500 px;

        display: flex;
        flex-flow: column;
        justify-content: space-between;
        align-items: flex-start;
        align-content: space-between;

    }
    i{
    font-size: 40px;
    color : white
    }
    </style>
	
  </head>

	<body> 
		
    {% include 'base.html' %}
    <div class="bg-image img1"></div>
    <div class="bg-text">
      <h2 style="color: #b3ffd5;  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">Biodata Singkat</h2>
      <table width="75%" style = " color: #f1f1f1; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
      <tr>
        <th><b>Nama</b></th>
        <th>Ian Andersen Ng</th>
        <th>
          <a href="https://www.instagram.com/ian.andersen.ng/"><i class="fab fa-instagram"></i></a>
        </th>
        <th>
          <a href="https://wa.me/62816833280"><i class="fab fa-whatsapp"></i></a>
        </th>
      </tr>
      <tr>
        <th><b>NPM</b></th>
        <th>1906400280</th>
      </tr>
      <tr>
        <th><b>Angkatan</b></th>
        <th><a href="https://maung.id/"><b>MAUNG</b></a>(2019)</th>
      </tr>
      <tr>
        <th><b>Tempat Kuliah</b></th>
        <th>Fakultas Ilmu Komputer Universitas Indonesia</th>
      </tr>
      <tr>
        <th><b>Hobi</b></th>
        <th>Bermain video games dan Baca Buku </th>
      </tr>
    </table>
    <h2 style="color: #b3ffd5; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">Deskripsi Tentang Saya</h2>
    <h4 style="color: #FFFFFF; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
     Saya lahir pada tanggal 20 Agustus 2001 di Jakarta. Saya lahir di rumah sakit Hermina Jakarta Utara. Saya merupakan anak pertama dari dua bersaudara . Adik saya berbeda 4 tahun lebih muda dari saya. Saya tidak pernah belajar programming sebelum masuk Fasilkom. Saya senang dan bangga saya masuk Fasilkom.
    </h4 >
    <h2 style="color: b3ffd5; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; ">Riwayat Pendidikan</h2>
    <table width="75%"  style = " color: #f1f1f1; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
      <tr>
        <th>2019-sekarang</th>
        <th>Universitas Indonesia</th>
      </tr>
      <tr>
        <th>2016-2019</th>
        <th>SMA Santa Theresia</th>
      </tr>
      <tr>
        <th>2013-2016</th>
        <th>Universal School</th>
      </tr>
      <tr>
        <th>2007-2013</th>
        <th>Universal School</th>
        
      </tr>
    </table>
   
    </div>
    
  </body>

</html>

homepage/templates/Story3.html
{% load static %}
<html>
    <title>Story3</title>
    <head>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body style="background-color: #0e0e0e;">
       
        <div class="jumbotron pt-0" id="homeku">
            {% include 'base.html' %}
            <div class = "container">
               <div class = "row h-100 align-items-center ">
                   <div class="col-lg-4 mx-auto">
                       <h1 class = "text-white text-center font-weight-bold">HI.</h1>
                       <h1 class = "text-white text-center font-weight-bold">HOLA.</h1>
                       <h1 class = "text-white text-center font-weight-bold">BONJOUR.</h1>
                   </div>
                </div>
           </div>
        </div>
        
        
        <!--About Me-->
        <div class="container" id="About_Me">
            <div class="row">
                <div class="title_green mx-auto mt-4 mb-5 ">
                    <h1>ABOUT ME</h1>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col ml-4 ml-md-0 mb-4 mb-md-0">
                    <img src = "{% static 'fotobw.jpg' %}" width="380px"; height="450px";>
                </div>
                <div class="col-sm-12 col-md-6 mx-3">
                    <h5 class="text-white text-justify">
                        My name is Ian Andersen Ng. 
                        I’m a tech enthusiast and I’m currently studying at Universitas Indonesia. 
                        My major is computer science. I have various hobbies such as gaming, coding, reading. 
                        I’ve studied different kinds of coding languages such as java and python. 
                        I’m able to make simple websites using html and css.
                    </h5 >
                    <br>
                    <h5 class="text-white text-justify">
                        My favorite kinds of book are autobiographies, psychology and self improvement books. 
                        My favorite foods are indonesian such as Siomay Bandung, Kwetiau goreng  and Bakso.  
                        I love the color green. I enjoy meeting new people with different kinds of opinions. 
                        I’m glad that i am able to make this website. Have fun exploring !!
                    </h5>
                </div>
            </div>
        </div>
        
        <!--Hobbies-->
        <div class="container" >
            <div class="row"id="Hobbies">
                <div class="title_purple mx-auto pt-5 mt-5 mb-5 ">
                   <h1>HOBBIES</h1>
                </div>
            </div>
            <div class="row">
                <div class="col mb-4 mb-md-0 text-center">
                    <img src = "{% static 'bukuhp.jpg' %}" width="350px"; height="250px";>
                </div>
                <div class="col-sm-12 col-md-6 mx-3">
                    <div class="title_green mb-5 ">
                        <h2>Reading</h2>
                    </div>
                    <h5 class="text-white text-justify">
                        I’ve read numerous amounts of books. 
                        I have been reading since fourth grade. 
                        During my childhood , I like to read graphic novels 
                        such Geronimo Stilton , Percy Jackson and Harry Potter . 
                        As I grow up I start to transition to non fiction. 
                        My favorite autobiography so far is written by Phil Jackson called Shoe Dog.
                        I’m currently reading Blink by Malcolm Gladwell.
                    </h5 >
                </div>  
            </div>
            <div class="row my-5">
                <div class="col mb-4 mb-md-0 text-center">
                    <img src = "{% static 'controllerhp.jpg' %}" width="350px"; height="250px";>
                </div>
                <div class="col-sm-12 col-md-6 mx-3">
                    <div class="title_purple mb-5">
                        <h2>Gaming</h2>
                    </div>
                    <h5 class="text-white text-justify">
                        
                            I’ve been playing console games since I was 10 years old. 
                            As a child I played lots of Naruto and Spongebob games on the Playstation2. 
                            Currently I’m playing lots of different 
                            games such as Apex Legends, God of War and Monster Hunter.
                        
                    </h5>
                </div>
                
            </div>
        </div>

        <!--Education-->
        <div class="container" id="Education">
            <div class="row">
                <div class="title_green mx-auto my-5 ">
                   <h1>EDUCATION</h1>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <img src = "{% static 'logo_uihp.png' %}" width="100px"; height="100px">
                </div>
                <div class="col text-white mt-4">
                    <h4>Currently Studying Computer Science in Universitas Indonesia</h4> 
                </div>
            </div>
            <div class="row">
                <div class="col text-center mt-5 ">
                    <img src = "{% static 'serviam-logo.png' %}" width="100px"; height="100px">
                </div>
                <div class="col text-white mt-5 pt-4">
                    <h4>SMA SANTA THERESIA 2016-2019</h4>
                </div>
            </div>
            <div class="row">
                <div class="col text-center mt-5">
                    <img src = "{% static 'universal.png' %}" width="100px"; height="100px">
                </div>
                <div class="col text-white mt-5 pt-4">
                    <h4>Universal School 2013-2016</h4>
                </div>
            </div>
        </div>

        <!--Contacts-->
        <div class="container-fluid mt-5" style = "background-color:2F2F2F ;" id="Contact">
            <div class = "row align-items-center pb-5">
                <div class="col text-white ml-4 mt-4 ">
                    Find me on:
                    <a href="https://www.instagram.com/ian.andersen.ng/"><img src="{% static 'insta.png' %}" width="30px" height="30px" style="color:#A3FB84">
                    <a href="https://wa.me/62816833280"><img src="{% static 'wa.png' %}" width="30px" height="30px" style="color:#6C69F9">
                </div>
                <div class="col text-white text-right mt-4">
                    Ian Andersen Ng
                    <img src="{% static 'logo.jpg' %}" width="30px" height="30px">
                </div>

            </div>
        </div>

    </body>
</html>

homepage/templates/Story3_Fav.html
{% load static %}
<html>
   
    <title>Story3 Favorite</title>
    <head>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        {% include 'base.html' %}
    </head>

    <!--Favorite Food-->
    <body style="background-color: #0e0e0e;">
        <div class="container" >
            <div class="row">
                <div class="title_purple mx-auto mb-5 ">
                   <h1>Favorite Food</h1>
                </div>
            </div>
            <div class="row">
                <div class="col mb-4 mb-md-0 text-center">
                    <img src = "{% static 'baksohp.jpg' %}" width="375px"; height="250px";>
                </div>
                <div class="col-sm-12 col-md-6 mx-3">
                    <div class="title_green mb-5 ">
                        <h2>Bakso</h2>
                    </div>
                    <h5 class="text-white text-justify">
                        Bakso or baso is an Indonesian meatball, or a meat paste made from beef surimi. 
                        Its texture is similar to the Chinese beef ball, fish ball, or pork ball. 
                        The word bakso may refer to a single meatball or the complete dish of meatball soup. 
                    </h5 >
                </div>
            </div>
            <div class="row my-5">
                <div class="col mb-4 mb-md-0 text-center">
                    <img src = "{% static 'martabakhp.jpg' %}" width="375px"; height="250px";>
                </div>
                <div class="col-sm-12 col-md-6 mx-3">
                    <div class="title_purple mb-5">
                        <h2>Martabak Telur</h2>
                    </div>
                    <h5 class="text-white text-justify">
                        Martabak is often described as spicy folded omelette pancake with bits of vegetables.
                        It is the most common form of Martabak; 
                        which is egg-filled pancake, 
                        sometimes mixed with green onion and minced meat, 
                        made from pan fried crepes which is folded and cut to squares. 
                        In Indonesia, the martabak is one of the most popular street foods and is known as Murtabak in other countries. 
                        
                    </h5>
                </div>
                
            </div>
        </div>

        <!--Contacts-->
        <div class="container-fluid mt-5" style = "background-color:2F2F2F ;">
            <div class = "row align-items-center pb-5">
                <div class="col text-white ml-4 mt-4 ">
                    Find me on:
                    <a href="https://www.instagram.com/ian.andersen.ng/"><img src="{% static 'insta.png' %}" width="30px" height="30px" style="color:#A3FB84">
                    <a href="https://wa.me/62816833280"><img src="{% static 'wa.png' %}" width="30px" height="30px" style="color:#6C69F9">
                </div>
                <div class="col text-white text-right mt-4">
                    Ian Andersen Ng
                    <img src="{% static 'logo.jpg' %}" width="30px" height="30px">
                </div>

            </div>
        </div>

    </body>
</html>

jadwal/templates/detail.html
{% load static %}
<html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Detail</title>
</head>
<body class="bg-dark text-white">

<div class="container mt-4">
    <h1>Detail</h1>
</div>
<div class="container" style="align: left">
    <div class="row mt-4">
       <div class="col" id="tulisan">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Mata Kuliah</th>
                    <th scope="col">Dosen</th>
                    <th scope="col">SKS</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Kelas</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">{{matkul.mata_kuliah}}</th>
                    <td>{{matkul.dosen_pengajar}}</td>
                    <td>{{matkul.jumlah_sks}}</td>
                    <td>{{matkul.deskripsi}}</td>
                    <td>{{matkul.semester_tahun}}</td>
                    <td>{{matkul.jam_kelas}}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="home d-flex justify-content-center">
        <a href="/">
            Home
        </a>
    </div>
</div>
</body>
</html>



</html>

jadwal/templates/jadwalku.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Jadwal</title>
</head>
<body class="bg-dark">
    <div class="container mt-4 text-white">
        <h1>Susun Jadwal</h1>
    </div>
    <div class="container text-white">
        <div class="row mt-4">
            <div class="col">
                <form action="" id ="form" method="POST">
                    {% csrf_token %}
                    {{ formulir }}
                    <input type = "submit" class="btn btn-primary my-5" value="Masukkan"> 
                    <div class="btn my-5">
                        <a href="/">
                            Home
                        </a>
                    </div>
                </form>
               
            </div>
            
            <div class="col">
                <div class="table-responsive" id="Table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Mata Kuliah</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        {% for i in jadwal %}
                        <tbody>
                            <tr>
                                <td>{{i.mata_kuliah}}</td>
                                <td><a href="{% url 'jadwal:hapus' pk=i.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash">Delete</i></button></a></td>
                                <td><a href="{% url 'jadwal:detail' pk=i.pk %}"> <button class="btn btn-info">Detail</button></a></td>
                                <td>
                                </td> 
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        
        </div>
    </div>
   
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <nav class="navbar navbar-expand-lg navbar-dark bg-transparent pt-4 ">

    <!-- Navbar brand --> 
    <img src="{% static 'logo.jpg' %}" class="logo" width="40px" height="40px py-0 my-0">
    
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            aria-expanded="false" aria-label="Toggle navigation py-0 my-0">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav py-0 my-0 ml-auto">
            <li class="nav-item active py-0">
                <a class="nav-link" href="{% url 'homepage:index' %}">Home
                    
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:favorit' %}">Favorites</a>
            </li><li class="nav-item">
                <a class="nav-link" href="{% url 'Story1_app:index' %}">Story1</a>
            </li>
          </li><li class="nav-item vertical-line">
            <a class="nav-link" href="{% url 'Story1_app:about' %}">Story1 About</a>
          </li><li class="nav-item vertical-line">
            <a class="nav-link" href="{% url 'jadwal:jadwal_url' %}">Susun Jadwal</a>
          </li>
            

        </ul>
        <!-- Links -->                
    </div>
    <!-- Collapsible content -->
  </nav>
</html>